/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.31
 * Generated at: 2020-04-22 03:30:43 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class RigsterPage_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1583199288978L));
    _jspx_dependants.put("jar:file:/C:/DataSource/FinalProject/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/FinalProject/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153356282000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("<meta charset=\"UTF-8\">\n");
      out.write("<title>註冊</title>\n");
      out.write("<!-- JQuery -->\n");
      out.write("<script src=\"https://code.jquery.com/jquery-3.4.1.min.js\"></script>\n");
      out.write("\n");
      out.write("<!-- TWzipcode -->\n");
      out.write("<script src=\"https://ajax.googleapis.com/ajax/libs/jquery/2.0.0/jquery.min.js\"></script>\n");
      out.write("\n");
      out.write("<!-- JQuery UI -->\n");
      out.write("<link rel=\"stylesheet\"\n");
      out.write("\thref=\"//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css\">\n");
      out.write("<script src=\"https://code.jquery.com/ui/1.12.1/jquery-ui.js\"></script>\n");
      out.write("<script src=\"https://code.jquery.com/jquery-3.4.1.js\"\n");
      out.write("\tintegrity=\"sha256-WpOohJOqMqqyKL9FccASB9O0KwACQJpFTUBLTYOVvVU=\"\n");
      out.write("\tcrossorigin=\"anonymous\"></script>\n");
      out.write("\n");
      out.write("<!-- style -->\n");
      out.write("<link\n");
      out.write("\thref=\"http://maxcdn.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css\"\n");
      out.write("\trel=\"stylesheet\" id=\"bootstrap-css\">\n");
      out.write("<link rel=\"stylesheet\"\n");
      out.write("\thref=\"https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css\"\n");
      out.write("\tintegrity=\"sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T\"\n");
      out.write("\tcrossorigin=\"anonymous\">\n");
      out.write("<link rel=\"stylesheet\"\n");
      out.write("\thref=\"https://use.fontawesome.com/releases/v5.0.8/css/all.css\">\n");
      out.write("<link rel=\"stylesheet\" href=\"css/register.css\">\n");
      out.write("\n");
      out.write("<script\n");
      out.write("\tsrc=\"http://cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js\"></script>\n");
      out.write("<script\n");
      out.write("\tsrc=\"http://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js\"></script>\n");
      out.write("<script\n");
      out.write("\tsrc=\"https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js\"\n");
      out.write("\tintegrity=\"sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM\"\n");
      out.write("\tcrossorigin=\"anonymous\"></script>\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("\t");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "fragment/indexTOP.jsp", out, false);
      out.write("\n");
      out.write("\n");
      out.write("\t<div class=\"container\">\n");
      out.write("\t\t<div class=\"card bg-light\">\n");
      out.write("\n");
      out.write("\t\t\t<article class=\"card-body mx-auto\" style=\"max-width: 800px;\">\n");
      out.write("\t\t\t\t<h4 class=\"rexColor1 card-title mt-3 text-center\">註冊會員</h4>\n");
      out.write("\t\t\t\t<p class=\"rexColor1 text-center\">Get started with your free\n");
      out.write("\t\t\t\t\taccount</p>\n");
      out.write("\t\t\t\t<form action=\"");
      if (_jspx_meth_c_005furl_005f0(_jspx_page_context))
        return;
      out.write("\" method=\"Post\" id=\"form1\" onsubmit=\"return checksubmit();\">\n");
      out.write("\t\t\t\t\t<div class=\"form-group input-group\">\n");
      out.write("\t\t\t\t\t\t<div class=\"input-group-prepend\">\n");
      out.write("\t\t\t\t\t\t\t<span class=\"input-group-text\"> <i class=\"fa fa-envelope\"></i>\n");
      out.write("\t\t\t\t\t\t\t</span>\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t<input id=\"userName\" name=\"email\" class=\"form-control\" type=\"email\"\n");
      out.write("\t\t\t\t\t\t\tplaceholder=\"(*)請輸入帳號(信箱)…\" autocomplete=\"off\" required=\"required\"\n");
      out.write("\t\t\t\t\t\t\ttitle=\"example@gmail.com\"  onblur=\"checkReg1()\" />\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t<!-- javaScript空標籤 -->\n");
      out.write("\t\t\t\t\t<p class=\"text-center rexColor1\">\n");
      out.write("\t\t\t\t\t\t<span id=\"img1\"></span><span id=\"txt1\"></span>\n");
      out.write("\t\t\t\t\t</p>\n");
      out.write("\t\t\t\t\t<!-- CheckReg()1 -->\n");
      out.write("\t\t\t\t\t<script type=\"text/javascript\">\t\t\t\t\t\n");
      out.write("\t\t\t\t\t\n");
      out.write("\t\t\t\t\t\t//表單送出時先驗證\n");
      out.write("\t\t\t\t\t\tfunction checksubmit(){\n");
      out.write("\t\t\t\t\t\t\tif(document.getElementById(\"txt1\").innerHTML==\"此帳號已重複\"){\n");
      out.write("\t\t\t\t\t\t\t\twindow.alert(\"帳號欄位不正確，請重新輸入\");\n");
      out.write("\t\t\t\t\t\t\t\treturn false;\n");
      out.write("\t\t\t\t\t\t\t}\n");
      out.write("\t\t\t\t\t\t\telse if(document.getElementById(\"pwd\").innerHTML!=\"\"){\n");
      out.write("\t\t\t\t\t\t\t\twindow.alert(\"密碼欄位不正確，請重新輸入\");\n");
      out.write("\t\t\t\t\t\t\t\treturn false;\n");
      out.write("\t\t\t\t\t\t\t}\n");
      out.write("\t\t\t\t\t\t\telse if(document.getElementById(\"repwd\").innerHTML!=\"\"){\n");
      out.write("\t\t\t\t\t\t\t\twindow.alert(\"二次密碼欄位不正確，請重新輸入\");\n");
      out.write("\t\t\t\t\t\t\t\treturn false;\n");
      out.write("\t\t\t\t\t\t\t}\n");
      out.write("\t\t\t\t\t\t\telse if(document.getElementById(\"nickName\").innerHTML!=\"\"){\n");
      out.write("\t\t\t\t\t\t\t\twindow.alert(\"暱稱欄位不正確，請重新輸入\");\n");
      out.write("\t\t\t\t\t\t\t\treturn false;\n");
      out.write("\t\t\t\t\t\t\t}\n");
      out.write("\t\t\t\t\t\t\telse if(document.getElementById(\"userId\").innerHTML!=\"\"){\n");
      out.write("\t\t\t\t\t\t\t\twindow.alert(\"身分證欄位不正確，請重新輸入\");\n");
      out.write("\t\t\t\t\t\t\t\treturn false;\n");
      out.write("\t\t\t\t\t\t\t}\n");
      out.write("\t\t\t\t\t\t\telse{\n");
      out.write("\t\t\t\t\t\t\t\treturn true;\n");
      out.write("\t\t\t\t\t\t\t}\n");
      out.write("\t\t\t\t\t\t}\n");
      out.write("\t\t\t\t\t\n");
      out.write("\t\t\t\t\t\n");
      out.write("\t\t\t\t\t\t// callback function\n");
      out.write("\t\t\t\t\t\tfunction checkReg1() {\n");
      out.write("\t\t\t\t\t\t\tvar rexEmail = /^\\w+((-\\w+)|(\\.\\w+))*\\@[A-Za-z0-9]+((\\.|-)[A-Za-z0-9]+)*\\.[A-Za-z]+$/;\n");
      out.write("\t\t\t\t\t\t\tvar imgValue = document.getElementById(\"img1\")\n");
      out.write("\t\t\t\t\t\t\tvar txtValue = document.getElementById(\"txt1\")\n");
      out.write("\t\t\t\t\t\t\tvar emailValue = document.getElementById(\"userName\").value\n");
      out.write("\t\t\t\t\t\t\t// 不能為空值\n");
      out.write("\t\t\t\t\t\t\tif (emailValue == \"\") {\n");
      out.write("\t\t\t\t\t\t\t\timgValue.innerHTML = '<i class=\"fa fa-times\">';\n");
      out.write("\t\t\t\t\t\t\t\ttxtValue.innerHTML = '帳號不能空白';\n");
      out.write("\t\t\t\t\t\t\t}\n");
      out.write("\t\t\t\t\t\t\t// Email格式驗證\n");
      out.write("\t\t\t\t\t\t\telse if (emailValue.search(rexEmail) == -1) {\n");
      out.write("\t\t\t\t\t\t\t\timgValue.innerHTML = '<i class=\"fa fa-times\">';\n");
      out.write("\t\t\t\t\t\t\t\ttxtValue.innerHTML = '錯誤Email格式';\n");
      out.write("\t\t\t\t\t\t\t} else {\n");
      out.write("\t\t\t\t\t\t\t\timgValue.innerHTML = \"\";\n");
      out.write("\t\t\t\t\t\t\t\ttxtValue.innerHTML = \"\";\n");
      out.write("\t\t\t\t\t\t\t\t$.ajax({\n");
      out.write("\t\t\t\t\t\t\t\t\turl : \"http://localhost:8080/FinalProject/check\",\n");
      out.write("\t\t\t\t\t\t\t\t\tdata : \"&email=\" + emailValue,\n");
      out.write("\t\t\t\t\t\t\t\t\ttype : \"GET\",\n");
      out.write("\t\t\t\t\t\t\t\t\tsuccess : function(data) {\n");
      out.write("\t\t\t\t\t\t\t\t\t\tvar status=eval(data);\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\n");
      out.write("\t\t\t\t\t\t\t\t\t\tif(status){\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\ttxtValue.innerHTML =\"\";\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\ttxtValue.innerHTML = \"此帳號已重複\";\n");
      out.write("\t\t\t\t\t\t\t\t\t\t}\n");
      out.write("\t\t\t\t\t\t\t\t\t\telse{\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\ttxtValue.innerHTML =\"\";\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\ttxtValue.innerHTML = \"可申請\";\n");
      out.write("\t\t\t\t\t\t\t\t\t\t}\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\n");
      out.write("\t\t\t\t\t\t\t\t\t}\n");
      out.write("\t\t\t\t\t\t\t\t})\t\n");
      out.write("\t\t\t\t\t\t\t}\n");
      out.write("\t\t\t\t\t\t\n");
      out.write("\t\t\t\t\t\t}\n");
      out.write("\t\t\t\t\t</script>\n");
      out.write("\t\t\t\t\t<!-- form-group// -->\n");
      out.write("\n");
      out.write("\t\t\t\t\t<div class=\"form-group input-group\">\n");
      out.write("\t\t\t\t\t\t<div class=\"input-group-prepend\">\n");
      out.write("\t\t\t\t\t\t\t<span class=\"input-group-text\"> <i class=\"fa fa-lock\"></i>\n");
      out.write("\t\t\t\t\t\t\t</span>\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t<input id=\"pwd\" name=\"password\" class=\"form-control\" type=\"password\"\n");
      out.write("\t\t\t\t\t\t\tplaceholder=\"(*)請輸入密碼…\" required=\"required\"\n");
      out.write("\t\t\t\t\t\t\ttitle=\"至少6個字且必須包含英文字母、數字\" onblur=\"checkReg2()\" />\n");
      out.write("\n");
      out.write("\t\t\t\t\t\t<!-- 二次密碼  -->\n");
      out.write("\n");
      out.write("\t\t\t\t\t\t<div class=\"input-group-prepend\">\n");
      out.write("\t\t\t\t\t\t\t<span class=\"input-group-text\"> <i class=\"fa fa-lock\"></i>\n");
      out.write("\t\t\t\t\t\t\t</span>\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t<input id=\"repwd\" class=\"form-control\" type=\"password\"\n");
      out.write("\t\t\t\t\t\t\tplaceholder=\"(*)二次密碼…\" onblur=\"checkReg3()\" required=\"required\"/>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t<!-- javaScript空標籤 -->\n");
      out.write("\t\t\t\t\t<div>\n");
      out.write("\t\t\t\t\t\t<p class=\"text-center rexColor1\" style=\"float: left;\">\n");
      out.write("\t\t\t\t\t\t\t<span class=\"rexColor1\">\n");
      out.write("\t\t\t\t\t\t\t\t<span id=\"img2\"></span><span id=\"txt2\"></span>\n");
      out.write("\t\t\t\t\t\t\t\t<span id=\"strong\" style=\"display:none\"></span>\n");
      out.write("\t\t\t\t\t\t\t</span>\n");
      out.write("\t\t\t\t\t\t</p>\n");
      out.write("\t\t\t\t\t\t<p class=\"text-center rexColor1\" style=\"float: right;\">\n");
      out.write("\t\t\t\t\t\t\t<span class=\"rexColor1\">\n");
      out.write("\t\t\t\t\t\t\t\t<span id=\"img3\"></span><span id=\"txt3\"></span>\n");
      out.write("\t\t\t\t\t\t\t</span>\n");
      out.write("\t\t\t\t\t\t</p>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t<!-- CheckReg2()、CheckReg3() -->\n");
      out.write("\t\t\t\t\t<script type=\"text/javascript\">\n");
      out.write("\n");
      out.write("\t\t\t\t\t\t// callback function\n");
      out.write("\t\t\t\t\t\tfunction checkReg2() {\n");
      out.write("\t\t\t\t\t\t\tvar rexEng = /[A-Za-z]/\n");
      out.write("\t\t\t\t\t\t\tvar rexNum = /[0-9]/\n");
      out.write("\t\t\t\t\t\t\tvar strValue = document.getElementById(\"strong\")\n");
      out.write("\t\t\t\t\t\t\tvar imgValue = document.getElementById(\"img2\")\n");
      out.write("\t\t\t\t\t\t\tvar txtValue = document.getElementById(\"txt2\")\n");
      out.write("\t\t\t\t\t\t\tvar pwdValue = document.getElementById(\"pwd\").value\n");
      out.write("\t\t\t\t\t\t\t//判斷密碼強度，總分9\n");
      out.write("\t\t\t\t\t\t\tvar score = 0;\n");
      out.write("\t\t\t\t\t\t\t//判斷大寫\n");
      out.write("\t\t\t\t\t\t\tvar rexBig = /[A-Z]/\n");
      out.write("\t\t\t\t\t\t\t//判斷小寫\n");
      out.write("\t\t\t\t\t\t\tvar rexLittle = /[a-z]/\n");
      out.write("\t\t\t\t\t\t\t//判斷特殊符號\n");
      out.write("\t\t\t\t\t\t\tvar pattern = new RegExp(\"[`~!@#$^&*()=|{}':;',\\\\[\\\\].<>《》/?~！@#￥……&*（）——|{}【】‘；：”“'。，、？]\");\t\n");
      out.write("\n");
      out.write("\t\t\t\t\t\t\t\n");
      out.write("\t\t\t\t\t\t\t// 不能為空值\n");
      out.write("\t\t\t\t\t\t\tif (pwdValue == \"\") {\n");
      out.write("\t\t\t\t\t\t\t\timgValue.innerHTML = '<i class=\"fa fa-times\">'\n");
      out.write("\t\t\t\t\t\t\t\ttxtValue.innerHTML = '密碼不能空白';\n");
      out.write("\t\t\t\t\t\t\t}\n");
      out.write("\t\t\t\t\t\t\t// 至少六個字\n");
      out.write("\t\t\t\t\t\t\telse if (pwdValue.length < 6) {\n");
      out.write("\t\t\t\t\t\t\t\timgValue.innerHTML = '<i class=\"fa fa-times\">'\n");
      out.write("\t\t\t\t\t\t\t\ttxtValue.innerHTML = '至少六個字';\n");
      out.write("\t\t\t\t\t\t\t}\n");
      out.write("\t\t\t\t\t\t\t// 判斷英文\n");
      out.write("\t\t\t\t\t\t\telse if (!rexEng.test(pwdValue)) {\n");
      out.write("\t\t\t\t\t\t\t\timgValue.innerHTML = '<i class=\"fa fa-times\">'\n");
      out.write("\t\t\t\t\t\t\t\ttxtValue.innerHTML = '沒有英文';\n");
      out.write("\t\t\t\t\t\t\t}\n");
      out.write("\t\t\t\t\t\t\t// 判斷數字\n");
      out.write("\t\t\t\t\t\t\telse if (!rexNum.test(pwdValue)) {\n");
      out.write("\t\t\t\t\t\t\t\timgValue.innerHTML = '<i class=\"fa fa-times\">'\n");
      out.write("\t\t\t\t\t\t\t\ttxtValue.innerHTML = '沒有數字';\n");
      out.write("\t\t\t\t\t\t\t} else {\n");
      out.write("\t\t\t\t\t\t\t\timgValue.innerHTML = \"\";\n");
      out.write("\t\t\t\t\t\t\t\ttxtValue.innerHTML = \"\";\n");
      out.write("\t\t\t\t\t\t\t}\n");
      out.write("\n");
      out.write("\t\t\t\t\t\t\t//密碼強度\n");
      out.write("\t\t\t\t\t\t\tif(txtValue.innerHTML==\"\"){\n");
      out.write("\t\t\t\t\t\t\t\t$(\"#strong\").css(\"display\",'');\n");
      out.write("\t\t\t\t\t\t\t\t\n");
      out.write("\t\t\t\t\t\t\t\tif (pwdValue.length >= 6) {\n");
      out.write("\t\t\t\t\t\t\t\t\tscore+=1;\n");
      out.write("\t\t\t\t\t\t\t\t\tif(pwdValue.length >= 10){\n");
      out.write("\t\t\t\t\t\t\t\t\t\tscore+=2;\n");
      out.write("\t\t\t\t\t\t\t\t\t}\n");
      out.write("\t\t\t\t\t\t\t\t\tif(rexNum.test(pwdValue)){\n");
      out.write("\t\t\t\t\t\t\t\t\t\tscore+=1;\n");
      out.write("\t\t\t\t\t\t\t\t\t}\n");
      out.write("\t\t\t\t\t\t\t\t\tif(rexBig.test(pwdValue)){\n");
      out.write("\t\t\t\t\t\t\t\t\t\tscore+=2;\n");
      out.write("\t\t\t\t\t\t\t\t\t}\n");
      out.write("\t\t\t\t\t\t\t\t\tif(rexLittle.test(pwdValue)){\n");
      out.write("\t\t\t\t\t\t\t\t\tscore+=1;\n");
      out.write("\t\t\t\t\t\t\t\t\t}\n");
      out.write("\t\t\t\t\t\t\t\t\tif(pattern.test(pwdValue)){\n");
      out.write("\t\t\t\t\t\t\t\t\t\tscore+=2;\n");
      out.write("\t\t\t\t\t\t\t\t\t}\n");
      out.write("\n");
      out.write("\t\t\t\t\t\t\t\t\tif(score<=3){\n");
      out.write("\t\t\t\t\t\t\t\t\t\tstrValue.innerHTML=\"密碼程度:弱\";\n");
      out.write("\t\t\t\t\t\t\t\t\t}\n");
      out.write("\t\t\t\t\t\t\t\t\telse if(score>3 && score<7){\n");
      out.write("\t\t\t\t\t\t\t\t\t\tstrValue.innerHTML=\"密碼程度:中\";\n");
      out.write("\t\t\t\t\t\t\t\t\t}\n");
      out.write("\t\t\t\t\t\t\t\t\telse{\n");
      out.write("\t\t\t\t\t\t\t\t\t\tstrValue.innerHTML=\"密碼程度:強\";\n");
      out.write("\t\t\t\t\t\t\t\t\t}\t\n");
      out.write("\t\t\t\t\t\t\t\t}\n");
      out.write("\t\t\t\t\t\t\t}\n");
      out.write("\t\t\t\t\t\t\telse{\n");
      out.write("\t\t\t\t\t\t\t\t$(\"#strong\").css(\"display\",'none');\n");
      out.write("\t\t\t\t\t\t\t}\t\n");
      out.write("\t\t\t\t\t\t\t\n");
      out.write("\t\t\t\t\t\t}\n");
      out.write("\t\t\t\t\t\t// callback function\n");
      out.write("\t\t\t\t\t\tfunction checkReg3() {\n");
      out.write("\t\t\t\t\t\t\tvar rexEng = /[A-Za-z]/\n");
      out.write("\t\t\t\t\t\t\tvar rexNum = /[0-9]/\n");
      out.write("\t\t\t\t\t\t\tvar imgValue = document.getElementById(\"img3\")\n");
      out.write("\t\t\t\t\t\t\tvar txtValue = document.getElementById(\"txt3\")\n");
      out.write("\t\t\t\t\t\t\tvar pwdValue = document.getElementById(\"pwd\").value\n");
      out.write("\t\t\t\t\t\t\tvar repwdValue = document.getElementById(\"repwd\").value\n");
      out.write("\t\t\t\t\t\t\t// 不能為空值\n");
      out.write("\t\t\t\t\t\t\tif (repwdValue == \"\") {\n");
      out.write("\t\t\t\t\t\t\t\timgValue.innerHTML = '<i class=\"fa fa-times\">'\n");
      out.write("\t\t\t\t\t\t\t\ttxtValue.innerHTML = '二次密碼不能空白';\n");
      out.write("\t\t\t\t\t\t\t}\n");
      out.write("\t\t\t\t\t\t\t// 至少六個字\n");
      out.write("\t\t\t\t\t\t\telse if (repwdValue.length < 6) {\n");
      out.write("\t\t\t\t\t\t\t\timgValue.innerHTML = '<i class=\"fa fa-times\">'\n");
      out.write("\t\t\t\t\t\t\t\ttxtValue.innerHTML = '至少六個字';\n");
      out.write("\t\t\t\t\t\t\t}\n");
      out.write("\t\t\t\t\t\t\t// 判斷英文\n");
      out.write("\t\t\t\t\t\t\telse if (!rexEng.test(repwdValue)) {\n");
      out.write("\t\t\t\t\t\t\t\timgValue.innerHTML = '<i class=\"fa fa-times\">'\n");
      out.write("\t\t\t\t\t\t\t\ttxtValue.innerHTML = '沒有英文';\n");
      out.write("\t\t\t\t\t\t\t}\n");
      out.write("\t\t\t\t\t\t\t// 判斷數字\n");
      out.write("\t\t\t\t\t\t\telse if (!rexNum.test(repwdValue)) {\n");
      out.write("\t\t\t\t\t\t\t\timgValue.innerHTML = '<i class=\"fa fa-times\">'\n");
      out.write("\t\t\t\t\t\t\t\ttxtValue.innerHTML = '沒有數字';\n");
      out.write("\t\t\t\t\t\t\t} \n");
      out.write("\t\t\t\t\t\t\t// 密碼相等\n");
      out.write("\t\t\t\t\t\t\telse if(repwdValue != pwdValue) {\n");
      out.write("\t\t\t\t\t\t\t\timgValue.innerHTML = '<i class=\"fa fa-times\">'\n");
      out.write("\t\t\t\t\t\t\t\ttxtValue.innerHTML = '二次密碼和密碼不同';\n");
      out.write("\t\t\t\t\t\t\t} else {\n");
      out.write("\t\t\t\t\t\t\t\timgValue.innerHTML = \"\";\n");
      out.write("\t\t\t\t\t\t\t\ttxtValue.innerHTML = \"\";\n");
      out.write("\t\t\t\t\t\t\t}\n");
      out.write("\t\t\t\t\t\t}\n");
      out.write("\t\t\t\t\t</script>\n");
      out.write("\t\t\t\t\t<!-- form-group// -->\n");
      out.write("\t\t\t\t\t\n");
      out.write("\t\t\t\t\t<div class=\"form-group input-group\">\n");
      out.write("\t\t\t\t\t\t<div class=\"input-group-prepend\">\n");
      out.write("\t\t\t\t\t\t\t<span class=\"input-group-text\"> <i class=\"fa fa-user\"></i>\n");
      out.write("\t\t\t\t\t\t\t</span>\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t<input id=\"nickName\" name=\"name\" class=\"form-control\" type=\"text\"\n");
      out.write("\t\t\t\t\t\t\t placeholder=\"(*)請輸入暱稱…\" maxlength=\"8\" required=\"required\"\n");
      out.write("\t\t\t\t\t\t\t onblur=\"checkReg4()\" autocomplete=\"off\" />\n");
      out.write("\n");
      out.write("\t\t\t\t\t\t<!-- 身分證  -->\n");
      out.write("\t\t\t\t\t\t\n");
      out.write("\t\t\t\t\t\t<div class=\"input-group-prepend\">\n");
      out.write("\t\t\t\t\t\t\t<span class=\"input-group-text\"><i class=\"fa fa-key\"></i></span>\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t<input id=\"userId\" name=\"id\" class=\"form-control\" type=\"text\"\n");
      out.write("\t\t\t\t\t\t\tplaceholder=\"(*)請輸入身分證…\" maxlength=\"10\" required=\"required\"\n");
      out.write("\t\t\t\t\t\t\tonblur=\"checkReg5()\"/>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t<!-- javaScript空標籤 -->\n");
      out.write("\t\t\t\t\t<div>\n");
      out.write("\t\t\t\t\t\t<p class=\"text-center rexColor1\" style=\"float: left;\">\n");
      out.write("\t\t\t\t\t\t\t<span class=\"rexColor1\">\n");
      out.write("\t\t\t\t\t\t\t\t<span id=\"img4\"></span><span id=\"txt4\"></span>\n");
      out.write("\t\t\t\t\t\t\t</span>\n");
      out.write("\t\t\t\t\t\t</p>\n");
      out.write("\t\t\t\t\t\t<p class=\"text-center rexColor1\" style=\"float: right;\">\n");
      out.write("\t\t\t\t\t\t\t<span class=\"rexColor1\">\n");
      out.write("\t\t\t\t\t\t\t\t<span id=\"img5\"></span><span id=\"txt5\"></span>\n");
      out.write("\t\t\t\t\t\t\t</span>\n");
      out.write("\t\t\t\t\t\t</p>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t<!-- CheckReg4()、CheckReg5() -->\n");
      out.write("\t\t\t\t\t<script type=\"text/javascript\">\n");
      out.write("\t\t\t\t\t\t// callback function\n");
      out.write("\t\t\t\t\t\tfunction checkReg4() {\n");
      out.write("\t\t\t\t\t\t\tvar rexMark = /[\\u0021-\\u002F\\u003A-\\u0040\\u005B-\\u0060\\u007B-\\u007E]/\n");
      out.write("\t\t\t\t\t\t\tvar imgValue = document.getElementById(\"img4\")\n");
      out.write("\t\t\t\t\t\t\tvar txtValue = document.getElementById(\"txt4\")\n");
      out.write("\t\t\t\t\t\t\tvar nickValue = document.getElementById(\"nickName\").value\n");
      out.write("\t\t\t\t\t\t\t// 不能為空值\n");
      out.write("\t\t\t\t\t\t\tif (nickValue == \"\") {\n");
      out.write("\t\t\t\t\t\t\t\timgValue.innerHTML = '<i class=\"fa fa-times\">'\n");
      out.write("\t\t\t\t\t\t\t\ttxtValue.innerHTML = '暱稱不能空白';\n");
      out.write("\t\t\t\t\t\t\t}\n");
      out.write("\t\t\t\t\t\t\t// 不能有標點符號 \n");
      out.write("\t\t\t\t\t\t\telse if (rexMark.test(nickValue)) {\n");
      out.write("\t\t\t\t\t\t\t\timgValue.innerHTML = '<i class=\"fa fa-times\">'\n");
      out.write("\t\t\t\t\t\t\t\ttxtValue.innerHTML = '不能有標點符號';\n");
      out.write("\t\t\t\t\t\t\t} else {\n");
      out.write("\t\t\t\t\t\t\t\timgValue.innerHTML = \"\";\n");
      out.write("\t\t\t\t\t\t\t\ttxtValue.innerHTML = \"\";\n");
      out.write("\t\t\t\t\t\t\t}\n");
      out.write("\t\t\t\t\t\t}\n");
      out.write("\t\t\t\t\t\t// callback function\n");
      out.write("\t\t\t\t\t\tfunction checkReg5() {\n");
      out.write("\t\t\t\t\t\t\tvar rexid = /^[a-z](1|2)\\d{8}$/i;\n");
      out.write("\t\t\t\t\t\t\tvar imgValue = document.getElementById(\"img5\")\n");
      out.write("\t\t\t\t\t\t\tvar txtValue = document.getElementById(\"txt5\")\n");
      out.write("\t\t\t\t\t\t\tvar idValue = document.getElementById(\"userId\").value\n");
      out.write("\t\t\t\t\t\t\t// 不能為空值\n");
      out.write("\t\t\t\t\t\t\tif (idValue == \"\") {\n");
      out.write("\t\t\t\t\t\t\t\timgValue.innerHTML = '<i class=\"fa fa-times\">'\n");
      out.write("\t\t\t\t\t\t\t\ttxtValue.innerHTML = '身分證不能空白';\n");
      out.write("\t\t\t\t\t\t\t}\n");
      out.write("\t\t\t\t\t\t\t// 至少十個字\n");
      out.write("\t\t\t\t\t\t\telse if (idValue.length < 9) {\n");
      out.write("\t\t\t\t\t\t\t\timgValue.innerHTML = '<i class=\"fa fa-times\">'\n");
      out.write("\t\t\t\t\t\t\t\ttxtValue.innerHTML = '字數不對';\n");
      out.write("\t\t\t\t\t\t\t}\n");
      out.write("\t\t\t\t\t\t\t// 格式驗證 \n");
      out.write("\t\t\t\t\t\t\telse if (!rexEng.test(idValue)) {\n");
      out.write("\t\t\t\t\t\t\t\timgValue.innerHTML = '<i class=\"fa fa-times\">'\n");
      out.write("\t\t\t\t\t\t\t\ttxtValue.innerHTML = '格式不符';\n");
      out.write("\t\t\t\t\t\t\t} else {\n");
      out.write("\t\t\t\t\t\t\t\timgValue.innerHTML = \"\";\n");
      out.write("\t\t\t\t\t\t\t\ttxtValue.innerHTML = \"\";\n");
      out.write("\t\t\t\t\t\t\t}\n");
      out.write("\t\t\t\t\t\t}\n");
      out.write("\t\t\t\t\t</script>\n");
      out.write("\t\t\t\t\t<!-- form-group// -->\n");
      out.write("\t\t\t\t\t\n");
      out.write("\t\t\t\t\t<div class=\"form-group input-group\">\n");
      out.write("\t\t\t\t\t\t<div class=\"input-group-prepend\">\n");
      out.write("\t\t\t\t\t\t\t<span class=\"input-group-text\"><i class=\"fa fa-tag\"></i></span>\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t<select id=\"gender\" class=\"form-control\" name=\"gender\">\n");
      out.write("\t\t\t\t\t\t\t<option value=\"\">請選擇性別</option>\n");
      out.write("\t\t\t\t\t\t\t<option value=\"男\">男</option>\n");
      out.write("\t\t\t\t\t\t\t<option value=\"女\">女</option>\n");
      out.write("\t\t\t\t\t\t</select>\n");
      out.write("\n");
      out.write("\t\t\t\t\t\t<!-- 出生年月日  -->\n");
      out.write("\n");
      out.write("\t\t\t\t\t\t<div class=\"input-group-prepend\">\n");
      out.write("\t\t\t\t\t\t\t<span class=\"input-group-text\"> <i class=\"fa fa-building\"></i>\n");
      out.write("\t\t\t\t\t\t\t</span>\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t<input id=\"birth\" name=\"birth\" class=\"form-control\" placeholder=\"出生年月日…\"\n");
      out.write("\t\t\t\t\t\t\ttype=\"date\">\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t<!-- form-group// -->\n");
      out.write("\n");
      out.write("\t\t\t\t\t<div class=\"form-group input-group\">\n");
      out.write("\t\t\t\t\t\t<div class=\"input-group-prepend\">\n");
      out.write("\t\t\t\t\t\t\t<span class=\"input-group-text\"><i\n");
      out.write("\t\t\t\t\t\t\t\tclass=\"fa fa-address-card\"></i></span>\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t<div id=\"twzipcode\" class=\"\">\n");
      out.write("\t\t\t\t\t\t\t<div class=\"f5\" data-role=\"county\"></div>\n");
      out.write("\t\t\t\t\t\t\t<div class=\"f6\" data-role=\"district\"></div>\n");
      out.write("\t\t\t\t\t\t\t<input id=\"address\" name=\"addr\" class=\"form-control\" type=\"text\"\n");
      out.write("\t\t\t\t\t\t\t\tplaceholder=\"(*)地址…\" size=\"25\" onblur=\"checkReg6()\" required=\"required\" />\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t<!-- javaScript空標籤 -->\n");
      out.write("\t\t\t\t\t<p class=\"text-center rexColor1\">\n");
      out.write("\t\t\t\t\t\t<span id=\"img6\"></span><span id=\"txt6\"></span>\n");
      out.write("\t\t\t\t\t</p>\n");
      out.write("\t\t\t\t\t<!-- CheckReg6() -->\n");
      out.write("\t\t\t\t\t<script src=\"https://cdn.jsdelivr.net/npm/jquery-twzipcode@1.7.14/jquery.twzipcode.min.js\"></script>\n");
      out.write("\t\t\t\t\t<script type=\"text/javascript\">\n");
      out.write("\t\t\t\t\t\t$(\"#twzipcode\").twzipcode({\n");
      out.write("\t\t\t\t\t\t\tzipcodeIntoDistrict: true,\n");
      out.write("\t\t\t\t\t\t\t\"css\": [\"city form-control\", \"town form-control\"],\n");
      out.write("\t\t\t\t\t\t\tcountyName: 'county', // 設定取得縣市的name\n");
      out.write("\t\t\t\t\t\t    districtName: 'district', // 設定取得鄉鎮市區的name\n");
      out.write("\t\t\t\t\t\t\t//  選擇縣市後執行\n");
      out.write("\t\t\t\t\t\t\tonCountySelect: function() {\n");
      out.write("\t\t\t\t\t\t\t\tvar county = $(\"select[name='county']\").val();\n");
      out.write("\t\t\t\t\t\t\t\t$(\"#address\").val(county);\n");
      out.write("\t\t\t\t\t\t\t},\n");
      out.write("\t\t\t\t\t\t\t//  選擇鄉鎮市區後執行\n");
      out.write("\t\t\t\t    \t  \tonDistrictSelect: function() {\n");
      out.write("\t\t\t\t    \t  \t\tvar district = $(\"select[name='district']\").val();\n");
      out.write("\t\t\t\t\t\t\t\tvar cityValue = $(\"#address\").val();\n");
      out.write("\t\t\t\t\t\t\t\taddrValue = cityValue + district;\n");
      out.write("\t\t\t\t\t\t\t\t$(\"#address\").val(addrValue);\n");
      out.write("\t\t\t\t\t\t\t}  \n");
      out.write("\t\t\t\t\t\t})\n");
      out.write("\t\t\t\t\t\t\n");
      out.write("\t\t\t\t\t\t// callback function\n");
      out.write("\t\t\t\t\t\tfunction checkReg6() {\n");
      out.write("\t\t\t\t\t\t\tvar rexChina = /^[\\u4E00-\\u9FA5]/\n");
      out.write("\t\t\t\t\t\t\tvar imgValue = document.getElementById(\"img6\")\n");
      out.write("\t\t\t\t\t\t\tvar txtValue = document.getElementById(\"txt6\")\n");
      out.write("\t\t\t\t\t\t\tvar addrValue = document.getElementById(\"address\").value\n");
      out.write("\t\t\t\t\t\t\t// 不能為空值\n");
      out.write("\t\t\t\t\t\t\tif (nickValue == \"\") {\n");
      out.write("\t\t\t\t\t\t\t\timgValue.innerHTML = '<i class=\"fa fa-times\">'\n");
      out.write("\t\t\t\t\t\t\t\ttxtValue.innerHTML = '地址不能空白';\n");
      out.write("\t\t\t\t\t\t\t}\n");
      out.write("\t\t\t\t\t\t\t// 必須有中文\n");
      out.write("\t\t\t\t\t\t\telse if (rexChina.test(addrValue)) {\n");
      out.write("\t\t\t\t\t\t\t\timgValue.innerHTML = '<i class=\"fa fa-times\">'\n");
      out.write("\t\t\t\t\t\t\t\ttxtValue.innerHTML = '必須有中文';\n");
      out.write("\t\t\t\t\t\t\t} else {\n");
      out.write("\t\t\t\t\t\t\t\timgValue.innerHTML = \"\";\n");
      out.write("\t\t\t\t\t\t\t\ttxtValue.innerHTML = \"\";\n");
      out.write("\t\t\t\t\t\t\t}\n");
      out.write("\t\t\t\t\t\t}\n");
      out.write("\t\t\t\t\t</script>\n");
      out.write("\t\t\t\t\t<!-- form-group// -->\n");
      out.write("\t\t\t\t\t<div class=\"form-group input-group\">\n");
      out.write("\t\t\t\t\t\t<div class=\"input-group-prepend\">\n");
      out.write("\t\t\t\t\t\t\t<span class=\"input-group-text\"> <i class=\"fa fa-phone\"></i>\n");
      out.write("\t\t\t\t\t\t\t</span>\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t<input id=\"ph\" name=\"tel\" class=\"form-control\" type=\"text\"\n");
      out.write("\t\t\t\t\t\t\t placeholder=\"請輸入電話…\" maxlength=\"10\">\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t<!-- form-group// -->\n");
      out.write("\n");
      out.write("\t\t\t\t\t<div class=\"form-group\">\n");
      out.write("\t\t\t\t\t\t<button type=\"submit\" class=\"btn btn-primary btn-block\">\n");
      out.write("\t\t\t\t\t\t\t註冊</button>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\n");
      out.write("\t\t\t\t\t<label ><input type=\"checkbox\" checked=\"checked\" name=\"ademail\" value=\"Y\"\n");
      out.write("\t\t\t\t\tstyle=\"margin-bottom: 15px;\">同意寄送最新產品廣告\n");
      out.write("\t\t\t\t\t</label>\n");
      out.write("\t\t\t\t\t\n");
      out.write("\t\t\t\t\t<!-- form-group// -->\n");
      out.write("\n");
      out.write("\t\t\t\t\t<p class=\"text-center\">\n");
      out.write("\t\t\t\t\t\t<!-- Button trigger modal -->\n");
      out.write("\t\t\t\t\t\t<label data-toggle=\"modal\" data-target=\"#exampleModalCenter\"><a\n");
      out.write("\t\t\t\t\t\t\thref=\"\">隱私權條款</a></label> 已經註冊過了? <a class=\"rexColor1\" href=\"loginSystem.jsp\"><b>登入</b></a>\n");
      out.write("\t\t\t\t\t</p>\n");
      out.write("\t\t\t\t\t<div>\n");
      out.write("\t\t\t\t\t\t<input type=\"button\" value=\"一鍵輸入\" onclick=\"input()\">\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t<p class=\"text-center rexColor1\">\n");
      out.write("\t\t\t\t\t\t<span id=\"img\"></span><span id=\"txt\"></span>\n");
      out.write("\t\t\t\t\t</p>\n");
      out.write("\t\t\t\t</form>\n");
      out.write("\t\t\t</article>\n");
      out.write("\t\t</div>\n");
      out.write("\t\t<!-- card.// -->\n");
      out.write("\t</div>\n");
      out.write("\t<!--container end.//-->\n");
      out.write("\n");
      out.write("\t<!-- Modal -->\n");
      out.write("\t<div class=\"modal fade\" id=\"exampleModalCenter\" tabindex=\"-1\"\n");
      out.write("\t\trole=\"dialog\" aria-labelledby=\"exampleModalCenterTitle\"\n");
      out.write("\t\taria-hidden=\"true\">\n");
      out.write("\t\t<div class=\"modal-dialog modal-lg\" role=\"document\">\n");
      out.write("\t\t\t<div class=\"modal-content\">\n");
      out.write("\t\t\t\t<div class=\"modal-header\">\n");
      out.write("\t\t\t\t\t<h5 class=\"modal-title\" id=\"exampleModalLongTitle\">隱私權條例</h5>\n");
      out.write("\t\t\t\t\t<button type=\"button\" class=\"close\" data-dismiss=\"modal\"\n");
      out.write("\t\t\t\t\t\taria-label=\"Close\">\n");
      out.write("\t\t\t\t\t\t<span aria-hidden=\"true\">&times;</span>\n");
      out.write("\t\t\t\t\t</button>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t\t<div class=\"modal-body\">\n");
      out.write("\t\t\t\t\t一、隱私權保護政策的適用範圍\n");
      out.write("\t\t\t\t\t隱私權保護政策內容，包括本網站如何處理在您使用網站服務時收集到的個人識別資料。隱私權保護政策不適用於本網站以外的相關連結網站，也不適用於非本網站所委託或參與管理的人員。\n");
      out.write("\t\t\t\t\t<br> <br> 二、個人資料的蒐集、處理及利用方式\n");
      out.write("\t\t\t\t\t當您造訪本網站或使用本網站所提供之功能服務時，我們將視該服務功能性質，請您提供必要的個人資料，並在該特定目的範圍內處理及利用您的個人資料；非經您書面同意，本網站不會將個人資料用於其他用途。\n");
      out.write("\t\t\t\t\t本網站在您使用服務信箱、問卷調查等互動性功能時，會保留您所提供的姓名、電子郵件地址、聯絡方式及使用時間等。\n");
      out.write("\t\t\t\t\t於一般瀏覽時，伺服器會自行記錄相關行徑，包括您使用連線設備的IP位址、使用時間、使用的瀏覽器、瀏覽及點選資料記錄等，做為我們增進網站服務的參考依據，此記錄為內部應用，決不對外公佈。\n");
      out.write("\t\t\t\t\t為提供精確的服務，我們會將收集的問卷調查內容進行統計與分析，分析結果之統計數據或說明文字呈現，除供內部研究外，我們會視需要公佈統計數據及說明文字，但不涉及特定個人之資料。\n");
      out.write("\t\t\t\t\t<br> <br> 三、資料之保護\n");
      out.write("\t\t\t\t\t本網站主機均設有防火牆、防毒系統等相關的各項資訊安全設備及必要的安全防護措施，加以保護網站及您的個人資料採用嚴格的保護措施，只由經過授權的人員才能接觸您的個人資料，相關處理人員皆簽有保密合約，如有違反保密義務者，將會受到相關的法律處分。\n");
      out.write("\t\t\t\t\t如因業務需要有必要委託其他單位提供服務時，本網站亦會嚴格要求其遵守保密義務，並且採取必要檢查程序以確定其將確實遵守。 <br>\n");
      out.write("\t\t\t\t\t<br> 四、網站對外的相關連結\n");
      out.write("\t\t\t\t\t本網站的網頁提供其他網站的網路連結，您也可經由本網站所提供的連結，點選進入其他網站。但該連結網站不適用本網站的隱私權保護政策，您必須參考該連結網站中的隱私權保護政策。\n");
      out.write("\t\t\t\t\t<br> <br> 五、與第三人共用個人資料之政策\n");
      out.write("\t\t\t\t\t本網站絕不會提供、交換、出租或出售任何您的個人資料給其他個人、團體、私人企業或公務機關，但有法律依據或合約義務者，不在此限。 <br>\n");
      out.write("\t\t\t\t\t<br> 前項但書之情形包括不限於：<br> <br> 1.經由您書面同意。<br> <br>\n");
      out.write("\t\t\t\t\t2.法律明文規定。<br> <br> 3.為免除您生命、身體、自由或財產上之危險。<br> <br>\n");
      out.write("\t\t\t\t\t4.與公務機關或學術研究機構合作，基於公共利益為統計或學術研究而有必要，且資料經過提供者處理或蒐集著依其揭露方式無從識別特定之當事人。\n");
      out.write("\t\t\t\t\t<br> <br>\n");
      out.write("\t\t\t\t\t當您在網站的行為，違反服務條款或可能損害或妨礙網站與其他使用者權益或導致任何人遭受損害時，經網站管理單位研析揭露您的個人資料是為了辨識、聯絡或採取法律行動所必要者。\n");
      out.write("\t\t\t\t\t有利於您的權益。 <br> <br>\n");
      out.write("\t\t\t\t\t本網站委託廠商協助蒐集、處理或利用您的個人資料時，將對委外廠商或個人善盡監督管理之責。 <br> <br>\n");
      out.write("\t\t\t\t\t六、Cookie之使用\n");
      out.write("\t\t\t\t\t為了提供您最佳的服務，本網站會在您的電腦中放置並取用我們的Cookie，若您不願接受Cookie的寫入，您可在您使用的瀏覽器功能項中設定隱私權等級為高，即可拒絕Cookie的寫入，但可能會導至網站某些功能無法正常執行\n");
      out.write("\t\t\t\t\t。 <br> <br> 七、隱私權保護政策之修正\n");
      out.write("\t\t\t\t\t本網站隱私權保護政策將因應需求隨時進行修正，修正後的條款將刊登於網站上。\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t\t<div class=\"modal-footer\">\n");
      out.write("\t\t\t\t\t<button type=\"button\" class=\"btn btn-secondary\"\n");
      out.write("\t\t\t\t\t\tdata-dismiss=\"modal\">關閉</button>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t</div>\n");
      out.write("\t</div>\n");
      out.write("\t<script type=\"text/javascript\">\n");
      out.write("\n");
      out.write("\t\tfunction input(){\n");
      out.write("\t\t\t\n");
      out.write("\t\t\t$(\"#userName\").val(\"w92532@hotmail.com\");\n");
      out.write("\t\t\t$(\"#pwd\").val(\"w41420\");\n");
      out.write("\t\t\t$(\"#repwd\").val(\"w41420\");\n");
      out.write("\t\t\t$(\"#nickName\").val(\"Vincent\");\n");
      out.write("\t\t\t$(\"#userId\").val(\"A123789456\");\n");
      out.write("\t\t\t$(\"#gender\").get(0).selectedIndex = 1;\n");
      out.write("\t\t\t$('#birth').val(\"2000-07-25\");\n");
      out.write("\t\t\t$(\"#address\").val(\"台北市中正區中正路10號\");\n");
      out.write("\t\t\t$(\"#ph\").val(\"0958744563\");\n");
      out.write("\t\t\tcheckReg1();\n");
      out.write("\t\t\tcheckReg2();\n");
      out.write("\t\t\tcheckReg4();\n");
      out.write("\t\t\tcheckReg5();\n");
      out.write("\t\t\t//form1.submit();\n");
      out.write("\t\t\t\n");
      out.write("\t\t}\n");
      out.write("\t\n");
      out.write("\t\tfunction showModal() {\n");
      out.write("\t\t\t$('#rule1').modal('show');\n");
      out.write("\t\t}\n");
      out.write("\n");
      out.write("\t</script>\n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005furl_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f0 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    boolean _jspx_th_c_005furl_005f0_reused = false;
    try {
      _jspx_th_c_005furl_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005furl_005f0.setParent(null);
      // /RigsterPage.jsp(54,18) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005furl_005f0.setValue("/signup");
      int _jspx_eval_c_005furl_005f0 = _jspx_th_c_005furl_005f0.doStartTag();
      if (_jspx_th_c_005furl_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f0);
      _jspx_th_c_005furl_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005furl_005f0, _jsp_getInstanceManager(), _jspx_th_c_005furl_005f0_reused);
    }
    return false;
  }
}
