/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.31
 * Generated at: 2020-04-13 08:23:05 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class RigsterPage_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(4);
    _jspx_dependants.put("/fragment/indexTOP.jsp", Long.valueOf(1586745184014L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1583199288978L));
    _jspx_dependants.put("/fragment/indexBOTTOM.jsp", Long.valueOf(1586701463000L));
    _jspx_dependants.put("jar:file:/C:/DataSource/FinalProject/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/FinalProject/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153356282000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("<meta charset=\"UTF-8\">\n");
      out.write("<title>RigsterPage</title>\n");
      out.write("\n");
      out.write("<script src=\"http://code.jquery.com/jquery-1.12.4.min.js\"></script>\n");
      out.write("\n");
      out.write("<style type=\"text/css\">\n");
      out.write("body {\n");
      out.write("\tbackground-color: #E8E8E8;\n");
      out.write("\tmargin: 0px;\n");
      out.write("\tpadding: 0px;\n");
      out.write("}\n");
      out.write("\n");
      out.write("#content {\n");
      out.write("\tbackground-repeat: no-repeat;\n");
      out.write("\tbackground-size: cover;\n");
      out.write("\theight: 1200px;\n");
      out.write("\tmargin-top: -21px;\n");
      out.write("\tmargin-bottom: 0px;\n");
      out.write("\tmargin: auto;\n");
      out.write("\twidth: 800px\n");
      out.write("}\n");
      out.write("\n");
      out.write("#rule:hover{\n");
      out.write("\tcursor: pointer;\n");
      out.write("}\n");
      out.write("\n");
      out.write("select {\n");
      out.write("\twidth: 99%;\n");
      out.write("\tpadding: 15px;\n");
      out.write("\tmargin: 5px 0 22px 0;\n");
      out.write("\tdisplay: inline-block;\n");
      out.write("\tborder: none;\n");
      out.write("\tbackground: #f1f1f1;\n");
      out.write("}\n");
      out.write("\n");
      out.write("/* Full-width input fields */\n");
      out.write("input[type=text], input[type=password],input[type=date] {\n");
      out.write("\twidth: 95%;\n");
      out.write("\tpadding: 15px;\n");
      out.write("\tmargin: 5px 0 22px 0;\n");
      out.write("\tdisplay: inline-block;\n");
      out.write("\tborder: none;\n");
      out.write("\tbackground: #f1f1f1;\n");
      out.write("}\n");
      out.write("\n");
      out.write("input[type=text]:focus, input[type=password]:focus {\n");
      out.write("\tbackground-color: #ddd;\n");
      out.write("\toutline: none;\n");
      out.write("}\n");
      out.write("\n");
      out.write("hr {\n");
      out.write("\tborder: 1px solid #f1f1f1;\n");
      out.write("\tmargin-bottom: 25px;\n");
      out.write("}\n");
      out.write("\n");
      out.write("/* Set a style for all buttons */\n");
      out.write("button {\n");
      out.write("\tbackground-color: #4CAF50;\n");
      out.write("\tcolor: white;\n");
      out.write("\tpadding: 14px 20px;\n");
      out.write("\tmargin: 8px 0;\n");
      out.write("\tborder: none;\n");
      out.write("\tcursor: pointer;\n");
      out.write("\twidth: 100%;\n");
      out.write("\topacity: 0.9;\n");
      out.write("}\n");
      out.write("\n");
      out.write("button:hover {\n");
      out.write("\topacity: 1;\n");
      out.write("}\n");
      out.write("\n");
      out.write("/* Extra styles for the cancel button */\n");
      out.write(".cancelbtn {\n");
      out.write("\tpadding: 14px 20px;\n");
      out.write("\tbackground-color: #f44336;\n");
      out.write("}\n");
      out.write("\n");
      out.write("/* Float cancel and signup buttons and add an equal width */\n");
      out.write(".cancelbtn, .signupbtn {\n");
      out.write("\tfloat: left;\n");
      out.write("\twidth: 50%;\n");
      out.write("}\n");
      out.write("\n");
      out.write("/* Add padding to container elements */\n");
      out.write(".container {\n");
      out.write("\tpadding: 16px;\n");
      out.write("}\n");
      out.write("\n");
      out.write("/* Clear floats */\n");
      out.write(".clearfix::after {\n");
      out.write("\tcontent: \"\";\n");
      out.write("\tclear: both;\n");
      out.write("\tdisplay: table;\n");
      out.write("}\n");
      out.write("\n");
      out.write("/* Change styles for cancel button and signup button on extra small screens */\n");
      out.write("@media screen and (max-width: 300px) {\n");
      out.write("\t.cancelbtn, .signupbtn {\n");
      out.write("\t\twidth: 100%;\n");
      out.write("\t}\n");
      out.write("}\n");
      out.write("</style>\n");
      out.write("\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("\n");
      out.write("\t");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("<meta charset=\"UTF-8\">\n");
      out.write("<title>indexTOP</title>\n");
      out.write("\n");
      out.write("<style type=\"text/css\">\n");
      out.write(".nav {\n");
      out.write("\tpadding-left:500px;\n");
      out.write("\tpadding-right:500px;\n");
      out.write("\tmargin-top: -19px;\n");
      out.write("\tmargin-bottom:0px;\n");
      out.write("\tbackground-color: #272727;\n");
      out.write("}\n");
      out.write("/* 主UL */\n");
      out.write(".navul {\n");
      out.write("\t\n");
      out.write("\tlist-style-type: none;\n");
      out.write("\tfont-weight: bolder;\n");
      out.write("\tfont-size: 20px;\n");
      out.write("\toverflow: auto;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".navul li {\n");
      out.write("\tborder-radius: 5px;\n");
      out.write("\tmargin-left: 0px;\n");
      out.write("\tmargin-right: 20px;\n");
      out.write("\tfloat: left;\n");
      out.write("\tdisplay: block;\n");
      out.write("\tposition: static;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".navul li a {\n");
      out.write("\ttext-decoration: none;\n");
      out.write("\tcolor: gray;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".navul li a:hover {\n");
      out.write("\tcolor: white;\n");
      out.write("}\n");
      out.write("\n");
      out.write("#navright {\n");
      out.write("\tfloat: right;\n");
      out.write("}\n");
      out.write("\n");
      out.write("\n");
      out.write("</style>\n");
      out.write("\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("\n");
      out.write("\t<nav id=\"navid\" class=\"nav\" style=\"text-align: center;\">\n");
      out.write("\t    \t\n");
      out.write("\t\t<ul class=\"navul\">\n");
      out.write("\t\t\t<li><a href=\"index.jsp\"><img alt=\"logo\" src=\"img/pineapple.jpg\"></a></li>\n");
      out.write("\t\t\t<li><a href=\"eyeMakPage.jsp\">eyeMak</a></li>\n");
      out.write("\t\t\t<li><a href=\"eyePadPage.jsp\">eyePad</a></li>\n");
      out.write("\t\t\t<li><a href=\"eyeFonePage.jsp\">eyeFone</a></li>\n");
      out.write("\n");
      out.write("\t\t\t<div id=\"navright\">\n");
      out.write("\t\t\t\t<li><a href=\"customerServicePage.jsp\">客服支援</a></li>\n");
      out.write("\t\t\t\t<li><a href=\"loginSystem.jsp\">登入</a></li>\n");
      out.write("\t\t\t\t<li><a href=\"shoppingcartPage.jsp\">購物車清單</a></li>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t</ul>\n");
      out.write("\t\t\n");
      out.write("\t</nav>\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<script type=\"text/javascript\">\n");
      out.write("\n");
      out.write("\n");
      out.write("</script>\n");
      out.write("</body>\n");
      out.write("</html>");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\t<div id=\"content\">\n");
      out.write("\t\t<form action=\"");
      if (_jspx_meth_c_005furl_005f0(_jspx_page_context))
        return;
      out.write("\" style=\"border: 1px solid #ccc\">\n");
      out.write("\t\t\t<div class=\"container\">\n");
      out.write("\t\t\t\t<h1>註冊</h1>\n");
      out.write("\t\t\t\t<p>請填寫此表格以創建一個帳戶。</p>\n");
      out.write("\t\t\t\t<hr>\n");
      out.write("\t\t\t\t\n");
      out.write("\t\t\t\t<label for=\"name\"><b>暱稱</b></label> <input type=\"text\"\n");
      out.write("\t\t\t\t\tplaceholder=\"10個以內的文字\" name=\"name\" > \n");
      out.write("\t\t\t\t\n");
      out.write("\t\t\t\t<label for=\"email\"><b>Email(帳號)</b></label> <input type=\"text\"\n");
      out.write("\t\t\t\t\tplaceholder=\"電子郵件信箱\" name=\"email\" > \n");
      out.write("\t\t\t\t\t\n");
      out.write("\t\t\t\t<label for=\"psw\"><b>密碼</b></label> <input type=\"password\"\n");
      out.write("\t\t\t\t\tplaceholder=\"8個以上包含半型英文和數字\" name=\"psw\" > \n");
      out.write("\t\t\t\t\t\n");
      out.write("\t\t\t\t<label for=\"psw-repeat\"><b>再次輸入密碼</b></label> <input type=\"password\"\n");
      out.write("\t\t\t\t\tplaceholder=\"8個以上包含半型英文和數字\" name=\"psw-repeat\" >\n");
      out.write("\t\t\t\t\t\n");
      out.write("\t\t\t\t\n");
      out.write("\t\t\t\t<label for=\"idnum\"><b>身分證號碼</b></label> <input type=\"text\"\n");
      out.write("\t\t\t\t\tplaceholder=\"身分證號碼\" name=\"idnum\" > \n");
      out.write("\t\t\t\t\n");
      out.write("\t\t\t\t\t\n");
      out.write("\t\t\t\t<label for=\"birthdate\"><b>出生年月日</b></label>\n");
      out.write("\t\t\t\t<input type=\"date\" id=\"birthdate\" name=\"birthdate\" placeholder=\"2014-09-18\">\t\n");
      out.write("\t\t\t\t\n");
      out.write("\t\t\t\t\n");
      out.write("\t\t\t\t<label for=\"sex\"><b>性別</b></label><br>\n");
      out.write("      \t\t\t\t<select  id=\"sex\" name=\"sex\">\n");
      out.write("        \t\t\t\t<option value=\"male\" selected>男</option>\n");
      out.write("        \t\t\t\t<option value=\"female\">女</option>\n");
      out.write("      \t\t\t\t</select><br>\n");
      out.write("\t\t\t\t\n");
      out.write("\t\t\t\t\n");
      out.write("\t\t\t\t<label for=\"tel\"><b>電話</b></label> <input type=\"text\"\n");
      out.write("\t\t\t\t\tplaceholder=\"電話號碼\" name=\"tel\" > \n");
      out.write("\t\t\t\t\t\n");
      out.write("\t\t\t\t\n");
      out.write("\t\t\t\t<label for=\"address\"><b>地址</b></label> <input type=\"text\"\n");
      out.write("\t\t\t\t\tplaceholder=\"地址\" name=\"address\" > \t\n");
      out.write("\t\t\t\t\n");
      out.write("\t\t\t\t\n");
      out.write("\t\t\t\t\n");
      out.write("\t\t\t\t\n");
      out.write("\t\t\t\t\t\n");
      out.write("\t\t\t\t \t\n");
      out.write("\t\t\t\t\n");
      out.write("      \t\t\t\n");
      out.write("      \t\t\t<!-- \n");
      out.write("      \t\t\t<label for=\"country\"><b>國家/地區</b></label><br>\n");
      out.write("      \t\t\t\t<select class=\"form-control\" id=\"country\" name=\"country\">\n");
      out.write("        \t\t\t\t<option value=\"taiwan\" selected>台灣</option>\n");
      out.write("        \t\t\t\t<option value=\"usa\">美國</option>\n");
      out.write("        \t\t\t\t<option value=\"japan\">日本</option>\n");
      out.write("        \t\t\t\t<option value=\"korea\">韓國</option>\n");
      out.write("        \t\t\t\t<option value=\"china\">中國</option>\n");
      out.write("      \t\t\t\t</select><br>\n");
      out.write("      \t\t\t\n");
      out.write("      \t\t\t\n");
      out.write("      \t\t\t<label for=\"timezone\"><b>時區</b></label><br>\n");
      out.write("      \t\t\t\t<select class=\"form-control\" id=\"timezone\" name=\"timezone\">\n");
      out.write("        \t\t\t\t<option value=\"UTC+8/tai\" selected>(UTC+8)taiwan</option>\n");
      out.write("        \t\t\t\t<option value=\"UTC-6\">UTC-6</option>\n");
      out.write("        \t\t\t\t<option value=\"UTC+9/jap\">(UTC+9)japan</option>\n");
      out.write("        \t\t\t\t<option value=\"UTC+9/kor\">(UTC+9)korea</option>\n");
      out.write("        \t\t\t\t<option value=\"UTC+8/ch\">(UTC+8)china</option>\n");
      out.write("      \t\t\t\t</select><br>\t\t\n");
      out.write("\t\t\t\t-->\t\n");
      out.write("\t\t\t\t\t\n");
      out.write("\t\t\t\t\t \n");
      out.write("\t\t\t\t\t\n");
      out.write("\t\t\t\t<label ><input type=\"checkbox\" checked=\"checked\" name=\"ad\"\n");
      out.write("\t\t\t\t\tstyle=\"margin-bottom: 15px;\">同意寄送最新產品廣告\n");
      out.write("\t\t\t\t</label>\n");
      out.write("\n");
      out.write("\t\t\t\t<p>\n");
      out.write("\t\t\t\t\t建立帳戶即表示您同意我們的 <label id=\"rule\" style=\"color: dodgerblue;\" onclick=\"rule()\">條款及細則和私隱政策</label>\n");
      out.write("\t\t\t\t</p>\n");
      out.write("\n");
      out.write("\t\t\t\t<div class=\"clearfix\">\n");
      out.write("\t\t\t\t\t<button type=\"reset\" class=\"cancelbtn\">清空</button>\n");
      out.write("\t\t\t\t\t<button type=\"submit\" class=\"signupbtn\">註冊</button>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t</form>\n");
      out.write("\t</div>\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\t");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("<meta charset=\"UTF-8\">\n");
      out.write("<title>indexBOTTOM</title>\n");
      out.write("\n");
      out.write("<style type=\"text/css\">\n");
      out.write("\t\n");
      out.write("\t#bottom{\n");
      out.write("\t\tbackground-color:#E8E8E8;\n");
      out.write("\t\ttext-align: center;\n");
      out.write("\t\tmargin-top: -17px;\n");
      out.write("\t\t\n");
      out.write("\t}\n");
      out.write("\t\n");
      out.write("</style>\n");
      out.write("\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("\t<div id=\"bottom\">\n");
      out.write("\t\t<p>© 2020 台灣sampple 版權所有。</p>\n");
      out.write("\n");
      out.write("\t\t<p>使用Internet Explorer 11、Chrome、Firefox及較新版本之瀏覽器去瀏覽本網站的效果最佳。</p>\n");
      out.write("\t</div>\n");
      out.write("</body>\n");
      out.write("</html>");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<script type=\"text/javascript\">\n");
      out.write("\n");
      out.write("\tfunction rule(){\n");
      out.write("\t\t\n");
      out.write("\t\twindow.open('rule.txt','newwindow')\n");
      out.write("\t\t\n");
      out.write("\n");
      out.write("//\t\t$.ajax({\n");
      out.write("//\t\t\turl:\"rule.txt\",\n");
      out.write("\t\t\t\n");
      out.write("//\t\t\tdataType:\"text\",\n");
      out.write("//\t\t\tsuccess:function(data){\n");
      out.write("\t\t\t\t\n");
      out.write("\t\t\t\t\n");
      out.write("//\t\t\t}\n");
      out.write("\n");
      out.write("//\t\t});\n");
      out.write("\t\t\n");
      out.write("\t\t\n");
      out.write("\t}\n");
      out.write("\t\n");
      out.write("\n");
      out.write("</script>\n");
      out.write("\n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005furl_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f0 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    boolean _jspx_th_c_005furl_005f0_reused = false;
    try {
      _jspx_th_c_005furl_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005furl_005f0.setParent(null);
      // /RigsterPage.jsp(117,16) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005furl_005f0.setValue("/signup");
      int _jspx_eval_c_005furl_005f0 = _jspx_th_c_005furl_005f0.doStartTag();
      if (_jspx_th_c_005furl_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f0);
      _jspx_th_c_005furl_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005furl_005f0, _jsp_getInstanceManager(), _jspx_th_c_005furl_005f0_reused);
    }
    return false;
  }
}
